#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
EXE="$ROOT/bin/ceretree"
BUN_BIN="$ROOT/build_cache/toolchains/bun-linux-x64/bun"

[ -x "$EXE" ] || exit 1
[ -x "$BUN_BIN" ] || exit 1

DESCRIBE_JSON="$("$EXE" '{"jsonrpc":"2.0","id":1,"method":"system.describe"}')"
printf '%s' "$DESCRIBE_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (data.result.name !== 'ceretree') process.exit(1); if (!data.result.languages.includes('go')) process.exit(1);"

ADD_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"roots.add\",\"params\":{\"paths\":[\"$ROOT\"]}}")"
printf '%s' "$ADD_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (!Array.isArray(data.result.roots) || data.result.roots.length < 1) process.exit(1);"

QUERY_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"query\",\"params\":{\"language\":\"go\",\"query\":\"(package_identifier) @name\",\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\"}}")"
printf '%s' "$QUERY_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (!Array.isArray(data.result.matches) || data.result.matches.length < 1) process.exit(1);"

INDEX_JSON="$("$EXE" '{"jsonrpc":"2.0","id":4,"method":"index.status"}')"
printf '%s' "$INDEX_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (!Array.isArray(data.result.roots) || data.result.roots.length < 1) process.exit(1); if (!data.result.last_query) process.exit(1);"

SYMBOLS_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"symbols.overview\",\"params\":{\"language\":\"go\",\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\",\"max_symbols\":20}}")"
printf '%s' "$SYMBOLS_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (!Array.isArray(data.result.files) || data.result.files.length < 1) process.exit(1); if (!Array.isArray(data.result.files[0].symbols) || data.result.files[0].symbols.length < 1) process.exit(1);"

FIND_SYMBOLS_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":6,\"method\":\"symbols.find\",\"params\":{\"language\":\"go\",\"name\":\"handle_query\",\"kinds\":[\"function\"],\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\"}}")"
printf '%s' "$FIND_SYMBOLS_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); const symbols = data.result.files.flatMap(file => file.symbols); if (!symbols.some(symbol => symbol.name === 'handle_query')) process.exit(1);"

PAGE_SYMBOLS_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":61,\"method\":\"symbols.find\",\"params\":{\"language\":\"go\",\"kinds\":[\"function\"],\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\",\"limit\":1,\"offset\":1}}")"
printf '%s' "$PAGE_SYMBOLS_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (data.result.summary.limit !== 1) process.exit(1); if (data.result.summary.offset !== 1) process.exit(1); if (data.result.summary.files_returned > 1) process.exit(1);"

CALLS_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":7,\"method\":\"calls.find\",\"params\":{\"language\":\"go\",\"callee\":\"invalid_params\",\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\"}}")"
printf '%s' "$CALLS_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); const calls = data.result.files.flatMap(file => file.calls); if (!calls.some(call => call.callee === 'invalid_params')) process.exit(1);"

PAGE_CALLS_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":71,\"method\":\"calls.find\",\"params\":{\"language\":\"go\",\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\",\"limit\":1}}")"
printf '%s' "$PAGE_CALLS_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (data.result.summary.limit !== 1) process.exit(1); if (data.result.summary.files_returned > 1) process.exit(1);"

COMMON_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":8,\"method\":\"query.common\",\"params\":{\"language\":\"go\",\"preset\":\"functions.by_name\",\"name\":\"handle_query\",\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\"}}")"
printf '%s' "$COMMON_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); const symbols = data.result.files.flatMap(file => file.symbols); if (!symbols.some(symbol => symbol.name === 'handle_query')) process.exit(1);"

PAGE_QUERY_JSON="$("$EXE" "{\"jsonrpc\":\"2.0\",\"id\":81,\"method\":\"query\",\"params\":{\"language\":\"go\",\"query\":\"(identifier) @name\",\"roots\":[\"$ROOT\"],\"include\":\"src/main.go\",\"limit\":1}}")"
printf '%s' "$PAGE_QUERY_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (data.result.summary.limit !== 1) process.exit(1); if (data.result.summary.files_returned > 1) process.exit(1);"

BOM_JSON="$("$BUN_BIN" -e "const body = '{\"jsonrpc\":\"2.0\",\"id\":11,\"method\":\"system.describe\"}'; process.stdout.write(Buffer.concat([Buffer.from([0xEF,0xBB,0xBF]), Buffer.from(body, 'utf8')]));" | "$EXE")"
printf '%s' "$BOM_JSON" | "$BUN_BIN" -e "const fs = require('node:fs'); const data = JSON.parse(fs.readFileSync(0, 'utf8')); if (data.id !== 11 || data.result.name !== 'ceretree') process.exit(1);"

"$BUN_BIN" -e "const fs = require('node:fs'); const path = require('node:path'); const root = process.argv[1]; const exe = process.argv[2]; const curlBin = process.platform === 'win32' ? 'curl.exe' : 'curl'; const socketPath = path.join(root, 'tests_cache', 'ceretree-http.sock'); const request1Path = path.join(root, 'tests_cache', 'ceretree-http-request-1.json'); const request2Path = path.join(root, 'tests_cache', 'ceretree-http-request-2.json'); try { fs.rmSync(socketPath, { force: true }); } catch {} fs.writeFileSync(request1Path, JSON.stringify({ jsonrpc: '2.0', id: 21, method: 'system.describe' })); fs.writeFileSync(request2Path, JSON.stringify({ jsonrpc: '2.0', id: 22, method: 'symbols.overview', params: { language: 'go', roots: [root], include: 'src/main.go', max_symbols: 5 } })); const server = Bun.spawn([exe, '--server', 'unix://' + socketPath], { cwd: root, stdout: 'ignore', stderr: 'pipe' }); const curl1 = Bun.spawnSync([curlBin, '--silent', '--show-error', '--retry', '20', '--retry-all-errors', '--retry-delay', '0', '--unix-socket', socketPath, '-H', 'content-type: application/json', '-X', 'POST', '--data-binary', '@' + request1Path, 'http://localhost/rpc']); const curl2 = Bun.spawnSync([curlBin, '--silent', '--show-error', '--retry', '5', '--retry-all-errors', '--retry-delay', '0', '--unix-socket', socketPath, '-H', 'content-type: application/json', '-X', 'POST', '--data-binary', '@' + request2Path, 'http://localhost/rpc']); server.kill(); try { fs.rmSync(socketPath, { force: true }); } catch {} if (curl1.exitCode !== 0 || curl2.exitCode !== 0) process.exit(1); const parsed1 = JSON.parse(Buffer.from(curl1.stdout).toString('utf8')); const parsed2 = JSON.parse(Buffer.from(curl2.stdout).toString('utf8')); if (parsed1.result.server_mode.active !== true) process.exit(1); if (!String(parsed1.result.server_mode.target).startsWith('unix://')) process.exit(1); if (!parsed1.result.server_mode.transports.includes('http+unix-socket')) process.exit(1); if (!Number.isInteger(parsed1.result.process_id)) process.exit(1); if (!Array.isArray(parsed2.result.files) || parsed2.result.files.length < 1) process.exit(1);" "$ROOT" "$EXE"

"$BUN_BIN" -e "const fs = require('node:fs'); const path = require('node:path'); const root = process.argv[1]; const exe = process.argv[2]; const curlBin = process.platform === 'win32' ? 'curl.exe' : 'curl'; const socketPath = path.join(root, 'tests_cache', 'ceretree-http-race.sock'); const request1Path = path.join(root, 'tests_cache', 'ceretree-http-race-request-1.json'); const request2Path = path.join(root, 'tests_cache', 'ceretree-http-race-request-2.json'); const response1Path = path.join(root, 'tests_cache', 'ceretree-http-race-response-1.json'); try { fs.rmSync(socketPath, { force: true }); } catch {} fs.writeFileSync(request1Path, JSON.stringify({ jsonrpc: '2.0', id: 23, method: 'system.describe' })); fs.writeFileSync(request2Path, JSON.stringify({ jsonrpc: '2.0', id: 24, method: 'index.status' })); const curl1 = Bun.spawn([curlBin, '--silent', '--show-error', '--retry', '20', '--retry-all-errors', '--retry-delay', '1', '--unix-socket', socketPath, '-H', 'content-type: application/json', '-X', 'POST', '--data-binary', '@' + request1Path, 'http://localhost/rpc'], { cwd: root, stdout: response1Path, stderr: 'pipe' }); Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 1200); const server = Bun.spawn([exe, '--server', 'unix://' + socketPath], { cwd: root, stdout: 'ignore', stderr: 'pipe' }); const curl1Exit = curl1.exited; const curl2 = Bun.spawnSync([curlBin, '--silent', '--show-error', '--retry', '5', '--retry-all-errors', '--retry-delay', '0', '--unix-socket', socketPath, '-H', 'content-type: application/json', '-X', 'POST', '--data-binary', '@' + request2Path, 'http://localhost/rpc']); server.kill(); try { fs.rmSync(socketPath, { force: true }); } catch {} if (curl1Exit !== 0 || curl2.exitCode !== 0) process.exit(1); const parsed1 = JSON.parse(fs.readFileSync(response1Path, 'utf8')); const parsed2 = JSON.parse(Buffer.from(curl2.stdout).toString('utf8')); if (parsed1.id !== 23) process.exit(1); if (parsed2.id !== 24) process.exit(1); if (parsed1.result.process_id !== parsed2.result.process_id) process.exit(1); if (!String(parsed1.result.server_mode.target).startsWith('unix://')) process.exit(1);" "$ROOT" "$EXE"

"$BUN_BIN" -e "const fs = require('node:fs'); const path = require('node:path'); const root = process.argv[1]; const exe = process.argv[2]; const curlBin = process.platform === 'win32' ? 'curl.exe' : 'curl'; const port = String(28000 + Math.floor(Math.random() * 10000)); const target = 'tcp://127.0.0.1:' + port; const requestPath = path.join(root, 'tests_cache', 'ceretree-tcp-request.json'); fs.writeFileSync(requestPath, JSON.stringify({ jsonrpc: '2.0', id: 31, method: 'index.status' })); const server = Bun.spawn([exe, '--server', target], { cwd: root, stdout: 'ignore', stderr: 'pipe' }); const curl = Bun.spawnSync([curlBin, '--silent', '--show-error', '--retry', '20', '--retry-all-errors', '--retry-delay', '0', '-H', 'content-type: application/json', '-X', 'POST', '--data-binary', '@' + requestPath, 'http://127.0.0.1:' + port + '/rpc']); server.kill(); if (curl.exitCode !== 0) process.exit(1); const parsed = JSON.parse(Buffer.from(curl.stdout).toString('utf8')); if (!Array.isArray(parsed.result.roots)) process.exit(1); if (!Number.isInteger(parsed.result.process_id)) process.exit(1);" "$ROOT" "$EXE"
