name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x build.sh test.sh
      - run: ./build.sh
      - run: ./test.sh

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - shell: cmd
        run: build.bat
      - shell: cmd
        run: test.bat
